# This is a basic workflow to help you get started with Actions

name: Example Workflow 
on:
push:
branches:
-main

jobs:
example-job:
runs-on: ubuntu-latest


steps:
-name: Checkout repository
users:actions/checkout@v2

-name:Use GitHub API with PAT
env:}}
run:
curl -H "Authorization: token $GITHUB_TOKEN" https://api:github.com/user
